apiVersion: v1
kind: Pod
metadata:
  labels:
    app: biba
  name: biba
spec:
  containers:
    - name: iperf
      image: docker.io/mishanya363/alpine-iperf3
      args:
      - /bin/sh
      - -c
      - "iperf3 -u -b 0 -c 10.244.1.2 -O 1 -f m -t 10"
      imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-node-2
  restartPolicy: Never
