apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bibaboba
  name: bibaboba
spec:
  containers:
  - name: iperf
    image: docker.io/mishanya363/alpine-iperf3
    args:
    - iperf3
    - -s
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-node-1
